// <auto-generated />
using System;
using Backend.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230720144010_CreateTable")]
    partial class CreateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMascota");

                    b.ToTable("Mascotas");

                    b.HasData(
                        new
                        {
                            IdMascota = 1,
                            Color = "Blanco",
                            Edad = 15,
                            FechaCreacion = new DateTime(2023, 7, 20, 9, 40, 10, 644, DateTimeKind.Local).AddTicks(2071),
                            Peso = 10f,
                            Raza = "PitBull"
                        },
                        new
                        {
                            IdMascota = 2,
                            Color = "Negra",
                            Edad = 20,
                            FechaCreacion = new DateTime(2023, 7, 20, 9, 40, 10, 644, DateTimeKind.Local).AddTicks(2084),
                            Peso = 10.5f,
                            Raza = "PitBull"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
