// <auto-generated />
using System;
using Backend.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Entidades.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMascota");

                    b.ToTable("Mascotas");

                    b.HasData(
                        new
                        {
                            IdMascota = 1,
                            Color = "Blanco",
                            Edad = 15,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2807),
                            Nombre = "Morgan",
                            Peso = 10f,
                            Raza = "PitBull"
                        },
                        new
                        {
                            IdMascota = 2,
                            Color = "Negra",
                            Edad = 20,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2819),
                            Nombre = "Niky",
                            Peso = 10.5f,
                            Raza = "PitBull"
                        },
                        new
                        {
                            IdMascota = 3,
                            Color = "Amarillo",
                            Edad = 5,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2820),
                            Nombre = "Doggo",
                            Peso = 25f,
                            Raza = "Labrador Retriever"
                        },
                        new
                        {
                            IdMascota = 4,
                            Color = "Dorado",
                            Edad = 7,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2822),
                            Nombre = "Bella",
                            Peso = 22f,
                            Raza = "Golden Retriever"
                        },
                        new
                        {
                            IdMascota = 5,
                            Color = "Negro y Marrón",
                            Edad = 4,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2823),
                            Nombre = "Rocky",
                            Peso = 30f,
                            Raza = "German Shepherd"
                        },
                        new
                        {
                            IdMascota = 6,
                            Color = "Naranja y Negro",
                            Edad = 2,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2824),
                            Nombre = "Simba",
                            Peso = 8f,
                            Raza = "Bengal Cat"
                        },
                        new
                        {
                            IdMascota = 7,
                            Color = "Gris",
                            Edad = 3,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2826),
                            Nombre = "Luna",
                            Peso = 10f,
                            Raza = "Maine Coon"
                        },
                        new
                        {
                            IdMascota = 8,
                            Color = "Negro",
                            Edad = 6,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2828),
                            Nombre = "Max",
                            Peso = 15f,
                            Raza = "Cocker Spaniel"
                        },
                        new
                        {
                            IdMascota = 9,
                            Color = "Tricolor",
                            Edad = 4,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2829),
                            Nombre = "Daisy",
                            Peso = 18f,
                            Raza = "Beagle"
                        },
                        new
                        {
                            IdMascota = 10,
                            Color = "Blanco y Marrón",
                            Edad = 1,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2831),
                            Nombre = "Milo",
                            Peso = 12f,
                            Raza = "Shih Tzu"
                        },
                        new
                        {
                            IdMascota = 11,
                            Color = "Blanco",
                            Edad = 5,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2832),
                            Nombre = "Whiskers",
                            Peso = 12f,
                            Raza = "Persian Cat"
                        },
                        new
                        {
                            IdMascota = 12,
                            Color = "Marrón y Blanco",
                            Edad = 3,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2834),
                            Nombre = "Rocky",
                            Peso = 28f,
                            Raza = "Boxer"
                        },
                        new
                        {
                            IdMascota = 13,
                            Color = "Atigrado",
                            Edad = 2,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2835),
                            Nombre = "Toby",
                            Peso = 20f,
                            Raza = "Bulldog Inglés"
                        },
                        new
                        {
                            IdMascota = 14,
                            Color = "Gris y Blanco",
                            Edad = 4,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2837),
                            Nombre = "Luna",
                            Peso = 25f,
                            Raza = "Siberian Husky"
                        },
                        new
                        {
                            IdMascota = 15,
                            Color = "Marrón",
                            Edad = 3,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2838),
                            Nombre = "Oliver",
                            Peso = 10f,
                            Raza = "Dachshund"
                        },
                        new
                        {
                            IdMascota = 16,
                            Color = "Gris y Blanco",
                            Edad = 2,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2840),
                            Nombre = "Nala",
                            Peso = 12f,
                            Raza = "Ragdoll"
                        },
                        new
                        {
                            IdMascota = 17,
                            Color = "Blanco y Marrón",
                            Edad = 5,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2841),
                            Nombre = "Jack",
                            Peso = 15f,
                            Raza = "Jack Russell Terrier"
                        },
                        new
                        {
                            IdMascota = 18,
                            Color = "Blanco",
                            Edad = 4,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2842),
                            Nombre = "Bella",
                            Peso = 9f,
                            Raza = "Poodle"
                        },
                        new
                        {
                            IdMascota = 19,
                            Color = "Negro y Marrón",
                            Edad = 6,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2844),
                            Nombre = "Rocky",
                            Peso = 35f,
                            Raza = "Rottweiler"
                        },
                        new
                        {
                            IdMascota = 20,
                            Color = "Blanco y Marrón",
                            Edad = 2,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2845),
                            Nombre = "Simba",
                            Peso = 7f,
                            Raza = "Siamese Cat"
                        },
                        new
                        {
                            IdMascota = 21,
                            Color = "Marrón",
                            Edad = 1,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2847),
                            Nombre = "Gizmo",
                            Peso = 4f,
                            Raza = "Chihuahua"
                        },
                        new
                        {
                            IdMascota = 22,
                            Color = "Blanco y Gris",
                            Edad = 3,
                            FechaCreacion = new DateTime(2023, 7, 20, 12, 23, 20, 779, DateTimeKind.Local).AddTicks(2848),
                            Nombre = "Luna",
                            Peso = 9f,
                            Raza = "Scottish Fold"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
